postmanlabs/newman

README.md
Added the -t, --testReportFile option as it wasn't specified in the Readme file.
=> Added missing -t option

bin/newman
Should point people to the organization repo
=> Switched CLI help text repository link to postmanlabs

.travis.yml, package.json
Simple version freezing, and run tests on node v0.12 too
=> improved version handling, and travis config

src/responseHandlers/TestResponseHandler.js, src/utilities/PreRequestScriptProcessor.js
For whatever reason, the sugar.number functions were missing from the sandbox, so I added them in real quick.
Not much testing other than the code I wrote using sugar.number that now works
related to the issue #214 I opened
=> Added missing sugar.number functions to newman

src/utilities/VariableProcessor.js, tests/utilities/VariableProcessor.js
=> ensure that function variable replacement is done on each iteration

bin/newman
=> Correct spelling issue

src/utilities/HelperProcessor.js
=> ensure that no body data is added if it is not present in the collection

src/utilities/ResponseExporter.js
=> add collection name to JUnit XML

src/utilities/HelperProcessor.js
=> Fix for issue #394

README.md
=> Added Slack Community link to README

.eslintrc, .travis.yml, README.md, bin/newman.js, lib/cli/TODO.md, lib/cli/index.js, lib/config/index.js, lib/config/process-env.js, lib/config/rc-file.js, lib/reporters/cli.js, lib/run.js, package.json, test/system/repository.test.js, test/system/travis-yml.test.js, test/unit/cli.test.js
Moved the currently unsupported options to `TODO.md`
=> Basic CLI support for v3

lib/cli/TODO.md, lib/cli/index.js, lib/run.js, package.json, test/system/nsp.test.js
* Specifying folder on the command line
* Request timeouts
* Request redirects
=> Added support for more options

lib/cli/TODO.md, lib/cli/index.js, lib/run.js, npm/test-system.js
=> Enabled [-d | --iteration-data] recognition for Newman v3

.editorconfig, CONTRIBUTING.md
=> Added CONTRIBUTING.md

lib/reporters/cli/cli-utils.js, lib/reporters/cli/index.js, lib/reporters/cli/print.js
* check presence of CI or lack of TTY and turn off interactive spinner
* turn off column width checking when window size is not found
> *merge https://github.com/postmanlabs/newman/pull/462 first*
Easy way to test this PR is piping newman to cat
`./bin/newman.js run examples/sample-collection.json | cat`
=> v3 => check tty and turn off spinner

lib/cli/index.js, test/unit/cli.test.js
=> Added a positive integer conformation check for iteration count

lib/reporters/cli/cli-utils.js, lib/reporters/cli/index.js, lib/reporters/cli/print.js, package.json, test/integration/redirect-test.postman_config.json
changes the console logs to be indented instead of separated by horizontal lines
=> v3 => indented console logs

lib/run.js, lib/util.js
- Newman was not accepting Objects when given in the configuration
- Ensure that Newman sends a User-Agent header when fetching stuff
=> Fixed two bugs

BETA.md, CONTRIBUTING.md, README.md, lib/cli/index.js, lib/reporters/cli/index.js, lib/run.js, lib/summary.js, npm/test-integration.js, npm/test-system.js
=> **V3** Fixed a bunch of typos

lib/reporters/cli/cli-utils.js, lib/reporters/cli/index.js, lib/reporters/cli/print.js, lib/run.js
affected
- spinner
- the numeric bullet separators
- hierarchy identifiers for requests
- folder identifier
- assertion pass identifier
=> v3 => windows utf8 graceful degradation

lib/run-config.js, lib/run.js, test/unit/run.test.js
- adds `beforeDone` event for later consumption in reporters
- moves run.js config loading to a separate file
> **DO NOT DELETE BRANCH POST MERGE **
=> v3 => beforeDone event and some code organisation

BETA.md, README.md, lib/cli/TODO.md, lib/cli/index.js, lib/export-file.js, lib/reporters/json/index.js, lib/run.js, lib/summary.js, lib/util.js, test/unit/run-summary.test.js
- separate export module
- support to export environment, collection, globals using the aforementioned export module
- JSON reporter which uses the export module
- README and BETA markdown updates
=> v3 => support for exporting globals, environment and collection

.gitignore, .npmignore, lib/reporters/emojitrain.js, lib/reporters/html/index.js, lib/reporters/json/index.js, lib/reporters/junit/index.js, lib/reporters/progress.js, lib/run/export-file.js, lib/run/index.js, lib/run/summary.js, package.json, test/unit/run-summary.test.js
1. reporter export path for defaults have now become optional
2. when nothing configured, export happens to `newman/` folder on pwd with default file name
3. existing files are overwritten
=> v3 => default reporter exports

lib/cli/index.js
Documentation has been added [here](https://github.com/postmanlabs/newman/blob/feature/v3-readme-finalisation/README.md#configuring-reporters).
=> Added "-r" as a reporter CLI option shorthand

MIGRATION.md, README.md, bin/newman.js, lib/cli/index.js, lib/run/index.js, test/unit/cli.test.js
* Changed `abortOnError` to `bail`
* Updated corresponding tests
* Added documentation for updated options
=> Corrected CLI inconsistencies

.eslintrc, bin/newman.js, examples/find-unique-urls-in-run.js, examples/read-collection-from-file.js, examples/run-collections-in-directory.js, lib/reporters/emojitrain.js, lib/version.js, npm/test-cli.js, npm/test-integration.js, npm/test-lint.js, npm/test-system.js, npm/test-unit.js, npm/test.js
=> Replaced console.log, with info/warn/error, added corresponding eslint config

lib/run/index.js, test/integration/tc4.postman_collection.json
=> File upload support

lib/run/index.js, test/integration/cookie-jar.postman_collection.json
=> Added cookie jar support, associated test

README.md, examples/reports/html-reporter-template-data.json, examples/reports/sample-collection-report.html, examples/reports/sample-collection-report.json, examples/reports/sample-collection-report.xml
* Corrected error in Newman library usage sample snippet
* Segregated sections using horizontal rules
> **TODO:**
=> Added table of contents to README.md

lib/reporters/html/index.js, lib/reporters/html/template-default.hbs
=> Fixed HTML reporter stats bug

README.md, appveyor.yml, test/cli/export-environment.test.js, test/cli/export-globals.test.js, test/cli/suppress-exit-code.test.js
=> Added Appveyor build configuration

test/cli/iteration-count.test.js
=> Added iterationCount tests

test/system/repository.test.js
=> Added npm script structure test

README.md
=> Improved documentation for multi-reporter usage

lib/reporters/html/index.js
=> Fixed html reporter bug

lib/reporters/junit/index.js
output correctly conforms to the XSD.
=> Fix for #687 - add tests attribute to the junit reporter this

lib/reporters/cli/cli-utils-symbols.js, lib/reporters/cli/index.js, test/unit/cli-reporter-symbols.test.js
=> Added specialist console log symbols

lib/reporters/html/index.js
https://github.com/postmanlabs/newman/pull/772#discussion_r89292749
=> Removed superfluous details from summary response object

examples/reports/html-reporter-template-data.json, lib/reporters/html/index.js
=> Added globals, env vars to html report template data

package.json
=> fix(package): update postman-runtime to version 3.0.9

package.json
=> fix(package): update filesize to version 3.5.4

package.json
=> chore(package): update eslint-plugin-lodash to version 2.3.3

package.json
=> fix(package): update postman-request to version 2.79.1-postman.4

test/integration/request-chaining-test.postman_collection.json
=> Added integration test for request var chaining

test/cli/run-options.test.js, test/fixtures/run/undefined-test-checks.json, test/library/run-options.test.js
https://github.com/postmanlabs/newman/issues/949
=> Tests #949

package.json
=> fix(package): update postman-collection to version 1.2.1

lib/reporters/cli/cli-utils.js
```json
{
"depth": 25,
"maxArrayLength": 100
}
```
=> Improved logging for deeply nested objects/long arrays

package.json
=> fix(package): update postman-runtime to version 6.1.4

lib/reporters/html/index.js, test/cli/shallow-html-reporter.test.js, test/fixtures/run/failed-request.json, test/library/shallow-html-reporter.test.js
=> HTML reporter failed request fix

package.json
=> fix(package): update postman-runtime to version 6.2.0

lib/run/summary.js, test/fixtures/run/response-bodies.json, test/fixtures/run/single-get-request.json, test/fixtures/run/single-request-failing.json, test/library/run-options.test.js
Discovered by @deyhle in #1037
=> Response body bugfix

package.json, test/library/run-options.test.js
=> fix(package): update postman-runtime to version 6.2.1

bin/newman.js, examples/parallel-collection-runs.js, lib/cli/index.js, lib/reporters/cli/index.js, lib/run/summary.js, package.json, test/cli/color-tty.test.js, test/cli/run-options.test.js, test/cli/shallow-html-reporter.test.js, test/cli/shallow-junit-reporter.test.js
=> chore(package): update eslint to version 4.1.1

package.json
=> fix(package): update postman-runtime to version 6.2.2

lib/reporters/html/index.js
=> Fixed Buffer construction issues on Node v4

lib/util.js, test/cli/run-options.test.js, test/library/run-options.test.js
=> Ensure that failed fetches from the Pro API result in a non zero exit code

package.json
=> fix(package): update postman-runtime to version 6.2.3

package.json
=> Update postman-runtime to version 6.2.4

package.json
=> Update postman-runtime to version 6.2.5

README.md, lib/cli/index.js, lib/run/options.js, test/cli/export-globals.test.js, test/cli/run-options.test.js, test/unit/cli.test.js
This pull request adds support for the inclusion of global variables via the CLI, addresses #1013.
=> Added support for CLI variables

package.json
=> Update xmlbuilder to version 9.0.3

package.json
=> Update postman-runtime to version 6.2.6

package.json
=> Update postman-runtime to version 6.3.0

package.json
=> Update postman-runtime to version 6.3.2

bin/newman.js
- Help text is shown in case of no command.
- Custom help message in case of any wrong command.
- Usage text specified properly for legacy arguments.
=> Improved help 

lib/run/index.js, package.json, test/fixtures/run/named-request.json, test/library/folder-variants.test.js, test/library/run-options.test.js
=> Fix folder parameter behavior

README.md
Slack -> Discourse
@numaanashraf @shamasis @kunagpal
=> Update ReadMe to Add Discourse Community Info

README.md, lib/reporters/cli/index.js
=> Fixed CLI no-assertion behaviour

package.json
=> fix(package): update xmlbuilder to version 9.0.6

README.md
Discovered in https://github.com/postmanlabs/newman/issues/1422
=> Corrected bail option documentation :memo:

.nsprc, package.json, test/system/nsp.test.js
=> fix(package): update postman-runtime to version 7.1.5

package.json
=> chore(package): update eslint-plugin-jsdoc to version 3.7.1

lib/reporters/html/template-default.hbs
Reverts postmanlabs/newman#1528
=> Revert "Unique folder & request IDs in HTML report template"

package.json, test/system/repository.test.js
=> Pinned applicable greenkeeper dependencies

package.json
=> chore(package): update parse-gitignore to version 0.5.1

.nsprc, lib/reporters/cli/index.js, package.json, test/system/nsp.test.js
Because third time's the charm
Resolves https://nodesecurity.io/advisories/577
=> CLI table the third

lib/reporters/junit/index.js, test/cli/shallow-junit-reporter.test.js, test/library/shallow-junit-reporter.test.js
=> Uniform junit report timing precision

npm/test-system.js, package.json, test/system/appveyor-yml.test.js, test/system/dockerfiles.test.js, test/system/editorconfig.test.js, test/system/jsdoc-config.test.js, test/system/nsp.test.js, test/system/repository.test.js, test/system/travis-yml.test.js
- Use chai expect assertions
- Add global expect for system test
=> Migrate System Tests to Chai

npm/test-unit.js, test/unit/cli-reporter-symbols.test.js, test/unit/cli.test.js, test/unit/options.test.js, test/unit/run-summary.test.js, test/unit/run.test.js, test/unit/util.test.js
- Use chai expect assertions
- Add global expect for unit test
=> Migrate Unit Tests to Chai

npm/test-library.js, package.json, test/library/cookie-sanity.test.js, test/library/export-environment.test.js, test/library/export-globals.test.js, test/library/folder-variants.test.js, test/library/iteration-count.test.js, test/library/run-options.test.js, test/library/shallow-html-reporter.test.js, test/library/shallow-junit-reporter.test.js, test/library/suppress-exit-code.test.js
- Use chai expect assertions
- Move chai to devDependencies
=> Migrate Library Tests to Chai

bin/newman.js, test/cli/shallow-html-reporter.test.js, test/cli/shallow-junit-reporter.test.js
=> CLI: Properly parse --reporter- argument

lib/reporters/html/index.js, lib/reporters/html/template-default.hbs
Closes https://github.com/postmanlabs/newman/issues/785
Before:
After:
=> Better HTML report timeout handling

lib/run/index.js
- Load external reporter before local reporter
- External reporter can overrides local reporter with same name
=> Update reporter load strategy

lib/run/index.js
=> Renamed knownReporters to knownReporterErrorMessages

lib/run/index.js
This makes the code consistent with the API docs
Fixes #1626
=> Updated default timeout values to Infinity :bug:

CHANGELOG.yaml
Reverts postmanlabs/newman#1648
=> Revert "Newman v4 CHANGELOG"

MIGRATION.md
Preview: https://github.com/postmanlabs/newman/blob/feature/migration/MIGRATION.md
=> Updated Migration Guide

CHANGELOG.yaml, MIGRATION.md, lib/run/index.js, lib/run/options.js, package.json, test/cli/run-options.test.js, test/integration/multi-level-folders-v1.postman_collection.json, test/unit/run.test.js
=>  Deprecate support for the v1 collection format

package.json
=> fix(package): update csv-parse to version 3.1.2

bin/newman.js, lib/run/options.js, test/cli/export-environment.test.js, test/cli/run-options.test.js, test/fixtures/overrides/env.json, test/fixtures/overrides/failing-collection.json, test/fixtures/overrides/pmcollection.json, test/unit/cli.test.js
#1799 and many others requested to have an extra flag to override environment variables.
=> Adds --env-var flag to override environment variables as key=value 

lib/reporters/cli/index.js, lib/run/summary.js
Previously min, max and s.d. values for response time were 0 always. The calculations for that are added now.
=> Fixed bug with calculations of standard deviation,average,min and max for response time

package-lock.json, package.json
=> Greenkeeper/eslint 5.15.3

test/integration/comma-test-csv/comma-test-csv.postman_collection.json, test/integration/comma-test-csv/comma-test-csv.postman_data.csv, test/integration/crypto-md5.postman_collection.json, test/integration/data-file-var-replacement/data-file-var-replacement.postman_collection.json, test/integration/data-file-var-replacement/data-file-var-replacement.postman_environment.json, test/integration/globals-env-data-files/globals-env-data-files.postman_environment.json, test/integration/multi-value-data.postman_collection.json, test/integration/steph/steph.postman_data.json, test/integration/super-sandbox-test.postman_collection.json, test/integration/v2-regression-tests/v2-regression-tests.postman_environment.json
Removes all references to my (or others') names from legacy integration tests
=> [WIP] - Remove all references to personal names from legacy tests

package-lock.json, package.json
=> Update postman-request to the latest version 🚀

.npmignore
Prevent addition of tests and config files in the published package, Refer #2026 
Closes #2231
=> Update .npmignore to prevent addition of tests and config files

CHANGELOG.yaml, lib/run/index.js, lib/run/options.js, lib/util.js, test/library/run-options.test.js, test/library/ssl-client-cert.test.js, test/unit/run.test.js
=> Improved error messages on file load error

CHANGELOG.yaml, README.md, lib/run/index.js, test/library/requestAgents.test.js
=> Added a new `requestAgents` option to define custom requesting agents

lib/crypt.js, test/unit/crypt.test.js
It adds the crypt library to encode/decode and encrypt/decrypt text.
This library will be used in the login command to store the API key.
1. Encryption is done using `AES-256` algorithm. Since it uses a key of size 256 bits, we first transform the given key to 256 bits using `SHA256` hashing.
2. Encoding is done using `Base-122` algorithm. The implementation of this algorithm is adapted from the following repo: https://github.com/kevinAlbs/Base122
The unit tests for the functions included are added.
=> Add crypt library

.eslintrc, lib/login/index.js, lib/logout/index.js, lib/print/index.js, package-lock.json, package.json, test/cli/login.test.js, test/cli/logout.test.js
This PR improves the user experience and the implementation of login and logout commands by using prompts module for user-prompts.
The user interaction in the commands after using this library is as follows:
- The CLI tests for these commands are updated.
=> Use prompts module for user-prompts in login and logout command

README.md
It adds documentation of the following features to the repo's README file.
1. Configuration files
2. Environment variables
3. `newman login` command
4. `newman logout` command
5. `sync-environment` option for run command
6. `postman-api-key-alias` option for run command
=> Add documentation for all the features included with Newman Login

README.md
**FIXES #2515  Redirection in BuildPassing Documentation**
**Before**
**After**
=> Fix redirection issue #2515

bin/newman.js, lib/reporters/cli/index.js, test/cli/request/large-size-data-handling.test.js
Added the capability to handle large sized data for single request.
=> Handling large data for single request

docker/images/alpine/Dockerfile
Resolves https://github.com/postmanlabs/newman/issues/2880
=> Update node to 16-alpine

README.md
Recently Allure created official newman reporter with support all of amazing features of newman. Let's add it to the readme 🚀
=> docs(reporters): Add allure reporter to readme
