postmanlabs/newman

- package.json
This PR consists changes to `package.json`
- all dependencies marked with `"*"` have been made to refer to the latest results of `npm install --save`
- forced `jsdom` dependency to `3.x.x`
The PR fixes issue with `jsdom 4` not supporting node in favour of io.js
> From jsdom package: "Note that as of our 4.0.0 release, jsdom no longer works with Node.js™, and instead requires io.js. You are still welcome to install a release in the 3.x series if you are stuck on legacy technology like Node.js™." ~ https://www.npmjs.com/package/jsdom
Otherwise, `jsdom@4.x` is resulting the following error:
```terminal
$ node --version
v0.10.26
$ npm --version
1.4.3
newman@1.2.12 node_modules/newman
├── commander@2.6.0
├── atob@1.1.2
├── btoa@1.1.2
├── node-uuid@1.4.1
├── tv4@1.1.9
├── underscore@1.8.2
├── …
```
> Updated `package.json` to better hold on to specific versions of dependencies

- bin/newman
- src/Newman.js
Add options to dump environment and globals(or environment) variables before newman exits to a file.
This allows the user to capture state of the environment and globals after a run for future reference (or use in subsequent invocations of newman or postman).
> Add options to dump environment and globals to files

- src/Newman.js
- src/responseHandlers/TestResponseHandler.js
- src/utilities/PreRequestScriptProcessor.js
Two changes:
ES6 has deprecated these properties, and replaced them with accessors that just throw a `TypeError` if you try to touch them.
My workaround is to simply copy entire file descriptors instead of using direct assignment. This way, you maintain enumerability, setters/getters, etc.
Seems like `iterationRunnerOver` was getting called before the `exec` callback, so I just added some flags to make sure we wait for that to finish before invoking the `Newman.execute` callback.
> More Node v4 stuff

- bin/newman
- src/models/RequestModel.js
- src/responseHandlers/AbstractResponseHandler.js
- src/utilities/Globals.js
This adds an optional feature to log (via appending) the full request and response bodies in to a text file.  
It also adds the method to the normal console logging.
Here's some sample output from the text file:
```
-------------------------------------------------------------------------------------------
200 3272ms Get status of server. [GET] http://localhost:8080/status
------------------------------------------------------------
Request headers:
{
"host": "localhost:8080"
}
Request body:
undefined
------------------------------------------------------------
Response headers:
{
"date": "Tue, 23 Jun 2015 19:11:14 GMT",
"x-request-id": "12345",
"x-request-size": "-1",
"x--server-id": "10.1.1.14",
"content-type": "application/json",
"connection": "close"
}
Response body:
{"Status":"OK" } …
```
> Log Request and Response Bodies

- Gruntfile.js
- README.md
- bin/newman
- src/utilities/Globals.js
- src/utilities/Logger.js
Feature request: #263 
-W option to enable black color for normal text.
> white screen: normal text has black color

- src/utilities/HelperProcessor.js
Collection properties for helper attributes lists 'service' not 'serviceName'.
```
"helperAttributes": {
"id": "awsSigV4",
...
...
"service": "s3",
"auto": true,
"saveHelper": true
},
```
This fixes a bug where 'execute-api' is used as part of Signature calculation
and failing.
> awsSignv4: Collection properties should be 'service' not 'serviceName'

- src/utilities/HelperProcessor.js
A patch related to this is pending upstream
- https://github.com/mhart/aws4/pull/21
With this change it would enable `newman` tool to be used
with AWS S3 compatible servers implementing AWS Signature
Version '4'.
> Add port and protocol for 'aws4' request inputs.

- src/utilities/CsvHelper.js
Hi, my requests sometimes require empty query parameter values, which I am importing from CSV. Postman does not have an issue with importing empty strings from CSV, but Newman was setting these values as Null. 
I'm sure there's a better way to solve this issue, but this little change works for me, so I figure I'd share.
Thanks!
Benjamin
> removed check for empty strings from CSV to be consistent with Postman

- README.md
- bin/newman
Just an idea, as a recent experience in our test environment bamboozled us by not realizing the difference in the request timeout between postman and newman (programatically set in CollectionRunner execute() towards the bottom). This value hasn't changed since April 13th of last year (0d6cf54dae831fd9ce3ce829ee282d0f7ecfd1ac), maybe documentation matching it may be helpful to some?
> Add help text for current default request timeout

- package.json
`_.now` not supported prior to v1.6
This is generally going to be ok for global installs but if you want newman installed locally in a project, this can lead to problems if an earlier version of underscore is already installed
> fix: underscore version is too loose

- README.md
Half of the Options table was colorized due to an apostrophe. removing that to keep the text all black
> Remove erroneous color from readme file

- .eslintrc
- README.md
- lib/config/index.js
- lib/reporters/cli.js
- lib/run.js
- lib/summary.js
`done` callback receives summary which looks somewhat like:
```
(
iterations: { total: 1, pending: 0, failed: 0 },
items: { total: 23, pending: 0, failed: 0 },
scripts: { total: 24, pending: 0, failed: 3 },
prerequests: { total: 23, pending: 0, failed: 3 },
requests: { total: 23, pending: 0, failed: 0 },
tests: { total: 23, pending: 0, failed: 0 },
assertions: { total: 62, pending: 0, failed: 8 },
failures: [{ source: 'DigestAuth Request', error: [Object] }]
}
```
Also adds `assertion` pseudo event and refactors CLI reporter to use the same.
Pending:
- Using the summary object to generate non failing summary like total requests, etc in CLI reporter
- Adding better location identification to failures in summary (such as line no, iteration, etc
- Doing row separation for multi-iteration …
> Run summary

- lib/reporters/cli/index.js
- lib/run.js
- lib/summary.js
While converting runtime callbacks to events, transform the arguments into a single object.
> emit as single object argument

- lib/reporters/cli/index.js
- lib/reporters/cli/print.js
- lib/run.js
This adds support to log console to terminal. Features
- data type is coloured
- objects are expanded and coloured recursively
- respects no-color flag
- prints neat boundary of console to avoid confusion
- colour coded boundary for log levels
Sample console.warn() with multiple arguments + object
Three subsequent console logs sharing common boundary
> v3 => console log

- bin/newman.js
- lib/node-version-check/index.js
- package.json
Did not put any check in preinstall. As we do not have any C++ bindings that cannot recompile if underlying node version is changed.
So, installation can follow on any version. but during usage, it errors out gracefully with appropriate console message. This allows easy usage with `n` or `nvm`.
> v3 => Added check in Newman CLI for node version check.

- lib/reporters/cli/cli-utils.js
- lib/reporters/cli/index.js
- `The LOG_WRAP_WIDTH` constant was off by 2 characters. Fixed it
- configured the `wrap` library to even break between words if needed.
> Fixed an issue with console log wrap width calculation

- lib/config/index.js
In case of missing `environment` or `globals` options, a default value of `{}` is used as a fallback. This allows proper handling of variables created during a collection run.
Takes care of #537.
> Fixed export bug

- CHANGELOG.md
- lib/cli/index.js
- lib/run/index.js
- lib/run/summary.js
- test/cli/export-environment.test.js
- test/cli/export-globals.test.js
- test/cli/simple-variables.json
- adds tests for export globals via CLI (need something for unit tests later TODO)
- fixes globals and environment export JSON structure (still missing env name or global name TODO)
- makes CLI accept param less `--export-*` so that default file names are used
Fixes #553
> Fix to export format of globals and environments

- lib/reporters/cli/cli-utils.js
- lib/reporters/cli/index.js
Related to #556 
A few points of interest:
* A table without borders is displayed for errors from a collection run, not sure if this is intended or was forgotten.
* There is a subtle difference in the way table output from `parseFailures` and `parseStatistics` is currently being handled in [lib/reporters/cli/index.js](https://github.com/postmanlabs/newman/blob/develop/lib/reporters/cli/index.js#L67#L72), as `.toString()` is not being called on `parseStatistics`
* The function signature for [parseStatistics](https://github.com/postmanlabs/newman/blob/develop/lib/reporters/cli/index.js#L170) should be compressed to one run object, and another for options.
* The [default cliTableTemplate](https://github.com/postmanlabs/newman/blob/develop/lib/reporters/cli/cli-utils.js#L18) has a …
> Added fallback CLI table for non unicode environments

- lib/run/options.js
**Context:** Newman library usage
This ensures that data / environments / globals options specified as objects within `newman.run` are still processed correctly.
> Allowed run options to be specified as objects

- lib/run/options.js
Takes care of #610 
**Context:** Newman Library usage
This ensures that V1 collections passed as objects are unconditionally converted to their respective V2 equivalents first.
> Fixed V1 collection resolution bug

- test/integration/super-sandbox-test.postman_collection.json
Randomly generated integers are now checked for the interval `>= 0`, instead of `> 1`.
> Fixed flaky sandbox integration test

- examples/reports/html-reporter-template-data.json
- examples/reports/sample-collection-report.html
- lib/reporters/cli/cli-utils.js
- lib/reporters/cli/index.js
- lib/reporters/html/index.js
- lib/reporters/html/template-default.hbs
- lib/util.js
Partly inspired by #763 
* Shifted `prettyms` and `filesize` methods to `lib/util.js`
* Updated CLI and HTML reporters to use new util helpers.
* Added average and response times, total data transferred, and overall run duration to HTML report.
* Updated sample data in examples/reports
> Added more details to HTML report

- README.md
- lib/cli/index.js
- lib/reporters/cli/cli-utils.js
> Added option to force colored output

- lib/reporters/html/index.js
- lib/reporters/html/partials/aggregations.hbs
- lib/reporters/html/template-default.hbs
> HTML report folder designation

- lib/reporters/html/partials/aggregations.hbs
* Folder headings have been made larger and shifted slightly to the left.
Before:
After:
> Better HTML report folder style

- README.md
Here, the `teamcity` reporter for newman has been used as an example. Inspired by https://github.com/postmanlabs/newman/issues/910, related to https://github.com/leafle/newman-reporter-teamcity/issues/1
> Added custom reporting documentation

- lib/reporters/junit/index.js
Resolves issue #862 Converting JUnit reporter responseTime from milliseconds to seconds
> Converting JUnit Reporter responseTime

- lib/run/options.js
- test/library/run-options.test.js
Inspired by #895
Context: Newman programmatic usage.
* With this pull request, `options.iterationData` can be specified as an array of objects as well.
> Objectified iteration data

- package.json
`v.2.2.0` was withdrawn from npmjs.org
> Bumped recursive-readdir to v2.2.1

- lib/reporters/html/index.js
- test/library/shallow-html-reporter.test.js
This does not mutate the original execution summary
> Restore HTML reporter response body

- .gitignore
- .npmignore
As JetBrains IDEs use .idea for IDE specific settings, Visual Studio Code uses .vscode.
These two one-line changes just add add .vscode to the .gitignore and .npmignore lists.
> Add Visual Studio Code's .vscode settings dir to ignore lists

- bin/newman.js
- package.json
- Added support for `-v` for version display.
- Modified help usage to correct the order of `<collection>` and `[options]` in help.
- Removed `argparse` from package.json
> Commander cleanup

- lib/run/index.js
Reusing the same error name from the error object from runtime in the constructed error object stack.
> Use error names from error object in the stack for the constructed psuedo error

- lib/run/options.js
All transformer calls will now use [v2.1.0](schema.getpostman.com/json/collection/v2.1.0/docs/index.html) as a target format.
> Use collection v2.1

- .github/ISSUE_TEMPLATE.md
Just a small spelling issue fix. The proper spelling is 'auxiliary'.
> Fix spelling in issue template

- bin/newman.js
- Fixes the legacy option order issue raised by @shamasis sir. 
- Basically, in case of legacy, the `process.argv.slice(2)` was removing the first two flags provided and they were not being added as options, the collection path was still being identified in case `-c` was the first option because of the fallback that checks for `options.collection` and if absent, takes the collection path from `rawArgs[1]` which was working fine for cases where `-c` was the first option.
- This was leading to any option supplied before `-c` as non-effective since it wasn't being added to the options list at all. 
- The proposed implementation modifies the `legacyMode` check and applies the slice operation only for run command options.
> Fixed legacy option ordering issue

- lib/reporters/junit/index.js
- test/fixtures/run/newman-report-test.json
- test/library/shallow-html-reporter.test.js
- test/library/shallow-junit-reporter.test.js
With this change, the JUnit reporter will add more information when AssertionErrors occur.
This is especially useful, when inspecting test reports in Jenkins (see screenshot).
Without this change: 
With this change:
> enhanced junit report with information about assertions of test scripts

- docker/README.md
Documentation about the alpine image is never referenced, add one.
> documentation: Add link to the alpine image

- README.md
- lib/reporters/cli/index.js
- test/unit/cli.test.js
Fixes #1588 
- Add `--reporter-cli-no-banner` flag
- Add Unit Test
- Update README
> Add no-banner option for CLI reporter

- .appveyor.yml
- .travis.yml
- lib/reporters/html/index.js
- package.json
- test/system/repository.test.js
- test/system/travis-yml.test.js
- Update travis and appveyor config
- Update package.json
- Update travis and repository tests
- Remove v4 Buffer support from HTML reporter
> Drop Node v4 support

- bin/newman.js
- lib/config/index.js
- lib/run/options.js
- lib/util.js
- package.json
- test/library/postman-api-key.test.js
- test/unit/cli.test.js
**Behavior:**
- Pass API key using `--postman-api-key` flag.
- External resources can be loaded using UID.
- Check for a valid UID first.
- Check if no file exists with the same UID name.
- Finally, check if `postmanApiKey` is present.
> Add ability to run collection via UID reference

- CHANGELOG.yaml
- MIGRATION.md
- README.md
- bin/newman.js
- lib/reporters/cli/cli-utils.js
- lib/reporters/cli/index.js
- test/cli/color-tty.test.js
- test/unit/cli.test.js
1. Drops support for `--no-color` CLI flag. Equivalent: `--color off`
2. Drops support for `noColor` Library options. Equivalent: `color: 'off'`
3. `--color` argument & `color` library option supports following value:
- auto (default) - chooses based on `process.env.CI` or `process.stdout.isTTY`
- on
- off
- anything other than these three falls back to `auto`.
**Todo:**
Reference: #1644 
Fixes #1636
> Update `color` flag behaviour

- npm/postpublish.sh
This will prevent the latest tag from being added to the images if the branch is not `master`.
> Improved Docker postpublish script to account for master branch

- lib/run/summary.js
Assertion summaries currently cover 2/3 possibilities for an assertion.
- If `error` is `undefined`, then it's assumed it `passed`
- Vice versa for error
If a test is skipped, it cannot be distinguished from a passed test at this level. This will be really useful for reporters where tests are aggregated/tabled, imagine a third column which would allow you to see what tests have skipped:
Whilst the `assertion` event contains the `skipped` status, there doesn't seem to be a clear way to join/aggregate assertions from `assertion` with `beforeDone`, so making `skipped` available within `assertions` on `beforeDone` seems to make most sense.
> Add skipped status to beforeDone assertion summary

- lib/reporters/junit/index.js
- test/cli/shallow-junit-reporter.test.js
- test/fixtures/run/nested-requests-fail-report-test.json
- test/fixtures/run/nested-requests-report-test.json
When given a collection with nested requests i.e requests in test scripts, Junit reporter is unable to generate a complete report. 
Fixes #1461
> Fix issue causing incomplete junit report to be generated for nested requests 

- README.md
Changes to the README:
- Selfishly added `htmlextra` to the example of how to use an external reporter
- Added some of the maintained community reporters
- Added another line to the Custom Reporter code which looked like it was missing
- Added a step for users to package and install the custom reporter rather than going straight to NPM
- Clean up of some typos and grammar mistakes
> Updated readme to add more community reporters

- README.md
I've found this command line option to be very useful and it looks like that there is no description for this option in the README, so this pull request adds that.
> Add description for --env-var command line option

- CHANGELOG.yaml
- lib/run/index.js
- test/unit/defaultReporter.test.js
- test/unit/externalReporter.test.js
Warning when reporter not found:
```
newman: "teamcity" reporter could not be found.
ensure that the reporter is installed in the same directory as newman
run `npm install newman-reporter-teamcity`
```
Warning when reporter could not be loaded:
```
newman: "cli" reporter could not be loaded.
this seems to be a problem in the reporter.
```
Ref: https://github.com/postmanlabs/newman/issues/1969
cc: @shamasis
> Add different warnings for reporter not found and reporter not loaded

- .github/CONTRIBUTING.md
Fixes #2238. 
There was no information about how to run `newman` in your local environment to the developers who are getting started with `nodejs` or `newman` in general. Also previously, apart from the tests, there was no clear way to debug any changes according to the documentation. I think it can be a viable option to use `console.log()` to debug changes at each step and running `node ./bin/newman <command-name>` before writing entire tests.
> update CONTRIBUTING.md to reflect how to run newman locally

- lib/run/options.js
- test/integration/comma-test-csv/comma-test-csv.postman_collection.json
- test/integration/comma-test-csv/comma-test-csv.postman_data.csv
- Previously `\` was used as an escape character which is changed to `"`
- Now it allows inconsistent columns count among rows in CSV files
- Use `relax` option of `csv-parse` library to allow using double quotes `"` without escaping inside an unquoted field.
> Changed escape character for CSV files to double quotes

- lib/config/index.js
- lib/config/rc-file.js
- test/unit/rc-file.test.js
It adds functions for loading and storing configurations from different RC files across the system.
1. The function for loading returns an empty object if the file doesn't exist.
2. The function for storing creates the file if it doesn't exist. 
- In *nix based systems, the new file created has read and write permissions only to the owner of the file.
- In Windows, since the file is stored in the User directory, it cannot be read by any other user.
1. The unit tests for both the functions are added.
- The whole testing process is done by changing the environment variable providing the home directory, to the `outDir` used in other tests.
> Add RC file controller

- .nycrc.js
- bin/newman.js
- lib/crypt.js
- lib/login/index.js
- lib/util.js
- test/cli/login.test.js
- test/unit/cli.test.js
It adds the login command.
```console
newman login
```
The command gets the following details by interaction:
1. Alias: The alias to be used to refer to the API Key.
2. API Key: The Postman-API-Key to get the resources from Postman-APIs.
3. Passkey(if any): If opted for one, stores the API Key in an encrypted form with the passkey provided used as the key to the encryption. If not provided, the API Key will be converted to its Base-122 encoding.
These details are formatted and stored in the RC file located in the home directory
The CLI and the parser tests for the login command are added.
> Add login command

- .nycrc.js
- bin/newman.js
- lib/logout/index.js
- lib/print/index.js
- test/cli/logout.test.js
- test/unit/cli.test.js
It adds the logout command. The command lists out all the alias available in the RC File located in the home directory and prompts the user to select an alias to delete.
```console
newman logout
```
- The CLI and parser tests for the command are added.
> Add logout command

- .nycrc.js
- bin/newman.js
- bin/util.js
- lib/config/defaults.js
- lib/config/index.js
- lib/run/options.js
- npm/test-cli.js
- npm/test-unit.js
- test/cli/login.test.js
- test/unit/cli.test.js
- test/unit/rc-file.test.js
Currently, details from RC-file and environment are loaded even for library runs.
This PR separates out code related to config sources from the library, to not let this happen.
Additionally, the PR makes sure that options mentioned in the RC File get higher priority than the default-options.
1. The `lib/config` module initially used in `lib/run/options.js` is now used in `bin/newman.js`.
2. An additional file `lib/config/defaults.js` is created to mention all the default options to give these options lesser priority than the ones in rc-file.
1. CLI-Parser tests are added to make sure proper merging of options take place from different sources.
2. The home directory is changed to `outDir` in CLI, unit test-suites to make sure the RC file used by the developers doesn't interfere in the …
> Fix: Alter logic to load config only for CLI-run

- lib/api/index.js
- lib/api/postman-resource.js
- lib/run/index.js
- lib/run/options.js
- lib/util.js
- test/library/postman-api-key.test.js
- test/unit/postman-resource.test.js
This PR adds API module to perform different operations using Postman APIs. It consists of a class representing a resource in Postman-Cloud like a collection or an environment. All the operations on a given Postman resource can be then done using member functions of the class like `get()`, `update()` etc.
- The module is integrated with `run` to fetch Postman collections and environments. 
- Once initialized before loading run-options, fetching of these resources can be done using the `get()` member function of the corresponding class instance.
- Each class instance also stores authentication details like postman-api-key. This apikey is either the apikey from the query-param of the URL or the session-api-key.
- Unit tests for the class are added.
- Library tests on postman-api-key option …
> Add API module to interact with Postman using APIs

- bin/newman.js
- lib/config/defaults.js
- lib/config/index.js
- lib/config/process-env.js
- lib/logout/index.js
- lib/util.js
- npm/test-cli.js
- test/cli/postman-api-key-alias.test.js
- test/unit/cli.test.js
It adds `postman-api-key-alias` option for `run` command along with its corresponding `environment` variable named `POSTMAN_API_KEY_ALIAS`. It is used to refer to a stored API Key by its alias.
Additionally, it also adds an `environment` variable named `POSTMAN_API_KEY` corresponding to the existing `postman-api-key` option.
1. The alias is only used when its absolutely required for authentication details.
For eg, the alias is not used in the following circumstances:
a. The API-Key is directly available through the option, env-variable or as a query parameter in the URL.
b. The collection referred to doesn't refer to a remote collection.
2. When the API-Key stored is encrypted, the user is prompted for a passkey to decrypt it.
3. When none of the aliases are referred and there is no …
> Add api-key-alias option

- bin/newman.js
- lib/api/postman-resource.js
- lib/run/index.js
- test/library/postman-api-key.test.js
- test/library/sync-environment.test.js
- test/unit/postman-resource.test.js
This PR adds an option named `sync-environment` for the run command. The option is used to update the environment in Postman-Cloud with the resultant environment of the run, given it represents a Postman Cloud resource. The option can also be used with the library run function.
``` console
$ newman run test_collection -e test_environment --sync-environment
```
Here the `test_environment` should either be a Postman API URL, a Postman-UID, or a Postman-ID of the environment.
The update is done using the `update` method of the PostmanResource Class.
The library tests for the option are added.
> Add sync-environment option for run command

- .nycrc.js
- bin/newman.js
- lib/login/index.js
- lib/logout/index.js
- lib/util.js
- test/cli/login.test.js
- test/cli/logout.test.js
- test/cli/postman-api-key-alias.test.js
This PR improves the user experience in dealing with stored API Keys. 
1. The login command now assumes that the alias is `default` if there is no data regarding it already stored. This way the user doesn't have to bother about the internal workings of the command.
2. If the `default` API Key already exists, the command will allow the user to either override it or create a new alias.
3. The logout command now gets user confirmation before deleting the API Key.
1. Better messages and prompts.
2. Improvement in the coloring of prompt messages.
3. Validation of the input for API Key
The CLI tests of the `login` command, `logout` command and `postman-api-key-alias` commands are updated.
> Improve login user experience

- lib/run/options.js
Going through the code base there was a todo marked at the `lib\run\options.js` in `iterationData` function to change the loading of iteration data to extension based loading. Following changes have been made in the file.
- remove `async.waterfall` function
- getting the file extension from the file location
- parsing the file according to the extension
- remove the import of `async` as it was no longer required
> add file extension based loading

- lib/util.js
NodeJS has deprecated the [Legacy URL API](https://nodejs.org/api/deprecations.html#deprecations_dep0116_legacy_url_api) which was being used in ```utils.js``` and recommends moving to the [WHATWG URL API](https://nodejs.org/api/url.html#url_the_whatwg_url_api).
I don't believe this change can fix https://github.com/postmanlabs/newman/issues/1991 but I'll be happy to look into it deeper.
> chore: update to WHATWG url api

- lib/reporters/cli/cli-utils.js
> Not rely on CI=true for TTY check

- CHANGELOG.yaml
- lib/run/index.js
The change is tiny and the code-diff would be self explanatory.
This cannot be documented as of yet, since runtime itself does not have enough documentation to leverage extensibility. However, it is a start and in a few iterations, the documentation can be improved.
For now, with this change, powerful reporters such as GIF attached below can be built.
> This exposes the `runner` on newman and the runtime `run` object in start event

- README.md
- The `/dashboard/integration` is an old link - integrations used to be within workspaces earlier, but has now moved to their own section in the app.
- Updated the link to point learning center docs for generating a postman API key
> Fixed the documentation link used for generating a postman api key

- package.json
This PR addresses Issue #3000
Due to missing dependencies in package.json newman cannot be used with Yarn PNP mode.
> Fix missing dependency which blocks Yarn PNP usage

- lib/reporters/cli/index.js
- test/cli/color-tty.test.js
We have to pass `border: []` to disable colors on the table.
- Fixes https://github.com/postmanlabs/newman/issues/3169
> Fix `--color off` not being respected in summary table

- README.md
Allure Report site is moved from https://qameta.io/allure-report/ to https://allurereport.org/. The suggested change updates the link
> Update Allure report site

- .github/workflows/ci.yml
- codecov.yml
> Add token for codecov

- CHANGELOG.yaml
- lib/util.js
- test/library/postman-api-key.test.js
The `apikey` query parameter is a deprecated way to authenticate requests on Postman API. This pull requests converts the query parameter in the url passed by the user, to the `x-api-key` header, before executing the request to Postman API
> Converted the deprecated `apikey` parameter in Postman API urls to `x-api-key` header

- lib/reporters/junit/index.js
Fixes #3230. 
According to [xmlbuilder-js CHANGELOG](https://github.com/oozcitak/xmlbuilder-js/blob/master/CHANGELOG.md), they
> Renamed `attributes` property to `attribs` to prevent name clash with DOM property with the same name.
This PR contains only this change.
> Changed xmlbuilder-js attributes for attribs on JUnit reporter
